site_name: MkDocs Template
site_url: https://example.com
site_author: username
nav:
  - Overview: index.md
  - Section I:
    - Chapter 1: section1/chapter1.md
    - Chapter 2: section1/chapter2.md
  - Section II:
    - Chapter 1: section2/chapter1.md
  - Others:
    - Wiki Hosting: others/wiki_hosting.md
    - Wiki Editing: others/wiki_edit.md
    - Math Example: others/math.md
    - Useful Links: others/links.md

plugins:
  - search

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png

  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode

    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode

    

  #font:
    #text: Underdog
    #text: Roboto
    #text: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - toc.follow
    - search.suggest
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - admonition
  
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: false
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
